id: 71470c3fbc554c03b5740cde3367cce4
initial_creation_type: ocr
source_metadata:
  volumes:
    312e8579b61e4bfe9ab930e761148467:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ''
      total_pages: 1953
      volume_number: 27
